version: "3.8"

services:

  postgres:
    container_name: unice_postgres
    image: postgres:14.0
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=X#wxpACw@c!WwUwb
      - POSTGRES_DB=unice
    ports:
      - "5432:5432"
    volumes:
      - unice_db_data:/var/lib/postgresql/data

volumes:
  unice_db_data:
    driver: local

networks:
  default:
    name: unice
