export const CONTROLLER_CONSTANTS = {
  AUTH: 'auth',
  USER: 'user',
  ORDER: 'order',
  COLLECTION: 'collection',
  UPLOAD: 'upload',
  COMMENT: 'comment',
  COMMENT_LIKE: 'comment-like',
  FOLLOWER: 'follower',
  SYSTEM_CONFIG: 'system-config',
};
export const URL_CONSTANTS = {
  CONNECT_WALLET: 'connect_wallet',
  CREATE_COLLECTION: 'create-collection',
  GET_COLLECTION_ID: '/:id',
  AUTH: 'auth',
  GET_CHART_BY_ADDRESS: 'chart/:symbol',
  HOLDER_DISTRIBUTION: 'holder/:id',
  UPLOAD_GCP: 'image/gcp',
  ORDER_HISTORY: 'history/:id',
  USER_ORDER_HISTORY: 'user/history/:id',
  ALL_SYMBOL: 'symbols/all',
  LIKE_COMMENT: 'like/:id',
  UNLIKE_COMMENT: 'unlike/:id',
  MARKET_CAP: 'market-cap/:id',
  SEARCH_COLLECTION_BY_NAME: '/search/name',
  LIST_COIN_HELD: 'list-coin/held/:address',
  LIST_COIN_CREATED: 'list-coin/created/:address',
  COMMENT_COLLECTION: ':id/comment',
  FOLLOW: 'follow',
  UNFOLLOW: 'unfollow',
  GET_FOLLOWERS: 'followers/:id',
  GET_FOLLOWING: 'following/:id',
  ADDRESS: '/:address',
  CHECK_FOLLOW: 'check-follow/:id',
  KING_OF_THE_HILL: '/board/king-of-the-hill',
  GET_CONTRACT_INFO: 'contract_info'
};
